const pullReqRoute = require('./pull-req-route.js')
const commitRoute = require('./commit-route.js')
const issuesRoute = require('./issues-route.js')
const getFinishedRoute = require('./get-finished-route.js')
const pullReq = require('./pullReq.js')
const createPost = require('./createPost.js');
const getAllProjects = require('./get-all-projects.js')
const getActiveProjects = require('./get-active-projects.js')
const getFinishedProjects = require('./get-finished-projects.js')
const addProject = require('./add-project.js')
module.exports = (app) => {
  //pullReqRoute(app, db)
  //pullReq(app)
  //commitRoute(app)
  //getFinishedRoute(app)
  //createPost(app)
  getAllProjects(app)
  getActiveProjects(app)
  getFinishedProjects(app)
  addProject(app)
  //issuesRoute(app)
}
